services:
  - type: web
    name: n8n
    env: node
    buildCommand: npm i -g pnpm && pnpm install
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 18.19.1
      - key: N8N_USER_FOLDER
        value: /opt/render/project/src/.n8n
