services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: npm i -g pnpm && pnpm install
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 18.19.1
